//! Key generation helpers exposed as CLI subcommands.
//!
//! Split into two commands on purpose. `gen-keys` is for standing up a new
//! deployment; `gen-jwt-key` is for rotating the signing key. Reusing
//! `gen-keys` to rotate would also regenerate `REFRESH_TOKEN_HMAC_KEY`, which
//! invalidates every stored refresh session and logs out every user — a much
//! bigger event than a key rotation is supposed to be.

use base64::Engine;
use base64::engine::general_purpose::STANDARD as B64;
use common::jwt::{generate_seed, public_key_for_seed, public_key_to_jwk_json};

fn random_key_b64() -> String {
    let mut key = [0u8; 32];
    rand::fill(&mut key);
    B64.encode(key)
}

/// Print a complete starter set of secrets.
pub fn gen_keys() {
    let seed = generate_seed();
    let kid = "k1";
    let jwk = public_key_to_jwk_json(kid, &public_key_for_seed(&seed));

    println!("# Generated by `api-backend gen-keys`. Store these as secrets.");
    println!("#");
    println!("# WARNING: REFRESH_TOKEN_HMAC_KEY must never be changed on a running");
    println!("# deployment — every refresh session is keyed by it, so rotating it logs");
    println!("# out every user. To rotate the JWT signing key later, use:");
    println!("#     api-backend gen-jwt-key --kid k2");
    println!();
    println!("JWT_ACTIVE_KID={kid}");
    println!("JWT_PRIVATE_KEY={}", B64.encode(seed));
    println!(r#"JWT_PUBLIC_KEYS={{"keys":[{jwk}]}}"#);
    println!("REFRESH_TOKEN_HMAC_KEY={}", random_key_b64());
    println!("REFRESH_SEAL_KEY={}", random_key_b64());
}

/// Print a new signing key for rotation, leaving other secrets alone.
pub fn gen_jwt_key(kid: &str) {
    if kid.is_empty()
        || kid.len() > 64
        || !kid
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        eprintln!("kid must be 1-64 characters of [A-Za-z0-9_-]");
        std::process::exit(2);
    }

    let seed = generate_seed();
    let jwk = public_key_to_jwk_json(kid, &public_key_for_seed(&seed));

    println!("# New JWT signing key. Roll it out in this order:");
    println!("#");
    println!("#  1. Add the JWK below to the existing JWT_PUBLIC_KEYS set (keep the old");
    println!("#     entry) and deploy BOTH api-backend and ws-gateway.");
    println!("#  2. Set JWT_PRIVATE_KEY and JWT_ACTIVE_KID together, then deploy");
    println!("#     api-backend. Changing only JWT_ACTIVE_KID fails the startup check.");
    println!("#  3. Remove the old JWK no sooner than 31 minutes after step 2 (30 min");
    println!("#     access-token lifetime + 30 s clock skew), or tokens still in flight");
    println!("#     will be rejected with an unknown-kid error.");
    println!("#");
    println!("# Do NOT regenerate REFRESH_TOKEN_HMAC_KEY as part of this.");
    println!();
    println!("JWT_ACTIVE_KID={kid}");
    println!("JWT_PRIVATE_KEY={}", B64.encode(seed));
    println!("# add to JWT_PUBLIC_KEYS \"keys\" array:");
    println!("{jwk}");
}
